# Generated by Django 4.1.6 on 2023-02-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articol', '0002_alter_category_options_articol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articol',
            old_name='name1',
            new_name='name',
        ),
    ]
